

name: Terraform CI

on:
  push:
    branches: [ main ]

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: production
    env:
      TERRAFORM_VERSION: "1.6.6"
      TF_COMMAND: "apply"
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1

    steps:
    # 1️⃣  Grab the code
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install AWS CLI
      run: |
        echo ${{ secrets.AWS_ACCESS_KEY_ID }}
        echo ${{ secrets.AWS_SECRET_ACCESS_KEY }}


  

    # 3️⃣  Install the requested Terraform CLI
    - name: Install Terraform ${{ env.TERRAFORM_VERSION }}
      run: |
        wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
        unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip
        sudo mv terraform /usr/local/bin/

    # 4️⃣  Init → validate → plan → apply
    - name: Terraform Init / Plan / ${{ env.TF_COMMAND }}
      run: |
        aws s3 ls
        cd terraform-manifests
        terraform init
        terraform validate
        terraform plan -lock=false -input=false -var-file=dev.tfvars
        terraform ${TF_COMMAND} -input=false -var-file=dev.tfvars   -auto-approve
